services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/collector-config.yml"]
    volumes:
      - ./collector-config.yml:/etc/collector-config.yml
    ports:
      - "4318:4318"
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"